#!/bin/sh
# shell script to prepend i3status with more stuff

i3status | while :
do
        read line
	
	MEMORY=$(free --mega -h)
	USED=$(echo "$MEMORY" | sed -n '1!p' | sed -n '2!p' | awk '{ print $3 }')
	TOTAL=$(echo "$MEMORY" | sed -n '1!p' | sed -n '2!p' | awk '{ print $2 }')
	
	RAM=" $USED of $TOTAL  ";

	CURRENTLY_PAYING="";
	PLAYER_STATUS=$(playerctl status)
	if [ "$PLAYER_STATUS" = "Playing" ]
	then
		ARTIST=$(playerctl metadata artist)
		SONG=$(playerctl metadata title)
		ALBUM=$(playerctl metadata album)

		CURRENTLY_PLAYING=" $ARTIST: $SONG  "
	fi

        echo "$CURRENTLY_PLAYING$RAM$line" || exit 1
done
