#!/bin/bash

ENTRIES=$(sqlite3 /home/gz/.mozilla/firefox/7wzsnqfc.default/places.sqlite "SELECT b.title || \" | \" ||  p.url  FROM moz_bookmarks b JOIN moz_places p ON b.fk = p.id" | rofi -i -dmenu)


IFS='| ' 
read -ra ADDR <<< "$ENTRIES"
for i in "${ADDR[@]}"; do
  URL=$i
done


echo "URL: '$URL'"

xdg-open "$URL"

