#!/bin/bash
SQL="SELECT b.title || \" | \" ||  p.url  FROM moz_bookmarks b JOIN moz_places p ON b.fk = p.id WHERE b.fk is not null AND b.title <> '' AND url <> '' AND url NOT LIKE 'place:%'"

PROFILE_FOLDER=/home/gz/snap/firefox/common/.mozilla/firefox/v2uzj9h7.default""
ENTRIES=$(sqlite3 ${PROFILE_FOLDER}/places.sqlite "${SQL}" | rofi -i -dmenu -p "Firefox bookmarks")


IFS=' | ' 
read -ra ADDR <<< "$ENTRIES"
for i in "${ADDR[@]}"; do
  URL=$i
done


echo "URL: '$URL'"

xdg-open "$URL"

