#!/bin/bash
SQL="SELECT b.title || \" | \" ||  p.url  FROM moz_bookmarks b JOIN moz_places p ON b.fk = p.id WHERE b.fk is not null AND b.title <> '' AND url <> '' AND url NOT LIKE 'place:%'"


PROFILE_DB=/home/gz/.mozilla/firefox/aluzwhkp.default/places.sqlite
TMP_PLACES=/tmp/places

#avoiding db lock
cp -f ${PROFILE_DB} ${TMP_PLACES}
ENTRIES=$(sqlite3 ${TMP_PLACES} "${SQL}" | rofi -i -dmenu -p "Firefox bookmarks")

rm ${TMP_PLACES}

IFS=' | ' 
read -ra ADDR <<< "$ENTRIES"
for i in "${ADDR[@]}"; do
  URL=$i
done


echo "URL: '$URL'"

xdg-open "$URL"

