#!/bin/bash
SQL="SELECT b.title || \" | \" ||  p.url  FROM moz_bookmarks b JOIN moz_places p ON b.fk = p.id WHERE b.fk is not null AND b.title <> '' AND url <> '' AND url NOT LIKE 'place:%'"

if [ -z "${FIREFOX_PROFILE+x}" ]; then
	echo "FIREFOX_PROFILE not set"
	exit 1
fi


PROFILE_DB=~/.mozilla/firefox/${FIREFOX_PROFILE}/places.sqlite
TMP_PLACES=/tmp/places

#avoiding db lock
cp -f ${PROFILE_DB} ${TMP_PLACES}
ENTRIES=$(sqlite3 ${TMP_PLACES} "${SQL}" | rofi -i -dmenu -p "Firefox")

echo "ENTRIES: ${ENTRIES}"
IFS=' | ' 
read -ra ADDR <<< "$ENTRIES"
for i in "${ADDR[@]}"; do
  URL=$i
done

if [[ $URL == http* ]]; then
	echo "URL: '$URL'"
else
	WORDS=$(echo ${ENTRIES} | wc -w)

	# we exit at empty string
	if [ $WORDS -eq 0 ]; then
		 exit 0
	 fi

	echo "${URL} is not url, using google search instead"
	URL="https://searx.ftpix.com?q=${ENTRIES}"
fi


xdg-open "$URL"

rm ${TMP_PLACES}
